package com.socialflow.ai.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

import java.util.List;

/**
 * Represents a single AI-generated post inside the suggested_entities payload
 * sent from the Python AI service to the Java callback endpoint.
 */
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class AiPostData {

    /** Post body text generated by the LLM. */
    private String content;

    /**
     * Filenames of AI-generated images already saved to disk by the Python service.
     * Empty list means no images were generated.
     */
    @JsonProperty("mediaFilenames")
    private List<String> mediaFilenames;

    /**
     * ISO-8601 datetime string for optional scheduled publishing.
     * Null or blank means the post is unscheduled (pure DRAFT).
     */
    @JsonProperty("scheduledTime")
    private String scheduledTime;

    /**
     * Human-readable platform hint from the LLM (e.g. "Facebook", "LinkedIn").
     * Informational only — the user picks the actual page on publish.
     */
    @JsonProperty("platform_suggestion")
    private String platformSuggestion;

    /**
     * The prompt that was used to generate the image.
     * Stored for auditing / regeneration purposes; not persisted to DB currently.
     */
    @JsonProperty("image_prompt")
    private String imagePrompt;
}
