
spring.application.name=SocialFlow

# Database - Neon PostgreSQL
# Replace with your Neon connection string
spring.datasource.url=jdbc:postgresql://ep-cool-cell-ailqmlxj-pooler.c-4.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_UHDBXn4Lo3jr&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_UHDBXn4Lo3jr
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=SocialFlowSuperSecretKeyThatIsAtLeast32BytesLong!!
jwt.expiration-ms=86400000

# Server
server.port=8080

# Base URL - dùng domain frontend vì chỉ expose 1 domain
# Khi deploy thay thành domain thật, VD: https://socialflow.yourdomain.com
app.base-url=https://popular-catfish-slightly.ngrok-free.app

# =============================================
# OAuth Credentials
# Replace with your actual app credentials
# =============================================

# Facebook
oauth.facebook.client-id=1867627970477000
oauth.facebook.client-secret=538b7c18250c8daca0e88b90b7110653
oauth.facebook.redirect-uri=${app.base-url}/api/oauth/facebook/callback

# Twitter / X (OAuth 1.0a keys)
oauth.twitter.consumer-key=GFDcURKfLe9XHl5isIXomwjSe
oauth.twitter.consumer-secret=1tXWt5CiCR8jqFPdvQnw4t6DJ8IKyMqDHbMNurrqDdJDCAU05x
oauth.twitter.bearer-token=AAAAAAAAAAAAAAAAAAAAAA6w7wEAAAAA1SRG8XYYyBv%2BV%2Fe3OC8xXAm2K7Y%3Dp1N22cXQdLkp2b7DTVURlJ8KxwiN2YDrukINYjZfndqa3iX8wm
# OAuth 2.0 Client ID
oauth.twitter.client-id=YWNhLVVCYzVEM0hPQlFZU0l0X0I6MTpjaQ
oauth.twitter.client-secret=5XIEj3hygfiIpWad0MntHvRgrQEDbc9dfXM_ZLhiSwQw52jkcy
oauth.twitter.redirect-uri=${app.base-url}/api/oauth/twitter/callback

# LinkedIn
oauth.linkedin.client-id=8699m096569jrb
oauth.linkedin.client-secret=WPL_AP1.SPAkJTzOLaUuE5zr.CxdeOw==
oauth.linkedin.redirect-uri=${app.base-url}/api/oauth/linkedin/callback

# Frontend URL (for OAuth callback redirects)
app.frontend-url=http://localhost:3000

# =============================================
# Webhook
# =============================================
# This token must match what you enter in Facebook App Dashboard > Webhooks > Verify Token
webhook.verify-token=socialflow_webhook_verify_2026

