apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: socialflow
type: Opaque
stringData:
  # Su dung Database Native (noi bo K3s)
  POSTGRES_PASSWORD: "__POSTGRES_PASSWORD__"
  DATABASE_URL: "postgresql://socialflow:__POSTGRES_PASSWORD__@postgres:5432/socialflow"