apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: socialflow
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/socialflow"
  SPRING_DATASOURCE_USERNAME: "socialflow"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SERVER_PORT: "8080"
  FRONTEND_URL: "https://socialflow.io.vn"