apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: socialflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: ecr-regcred
      containers:
      - name: frontend
        image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/socialflow/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          value: "http://backend:8080"
        - name: NEXT_PUBLIC_API_URL
          value: "https://socialflow.io.vn"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"